msrv = "1.70"
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 8
type-complexity-threshold = 250
trivial-copy-size-limit = 64
pass-by-value-size-limit = 256
too-many-lines-threshold = 100
avoid-breaking-exported-api = false
suppress-restriction-lint-in-const = false